version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timedb
      POSTGRES_USER: user
    volumes:
      - ./data:/var/lib/postgresql
      - ./pg-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - database-network
  backend:
    image: bachelor-backend
    depends_on:
      - postgres
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
    external: false

